### ISSUE TITLE
Repeat Entry Harvest Error

### ISSUE THREAD

**Issue by lbross** [LANDIS-II-Foundation/Library-Harvest-Mgmt#3]
Reported by lbross@pdx.edu, Nov 7, 2014
Let prescriptions be called again before all entries are completed for previously called prescriptions. This affects single-repeat harvests, and there is a related bug in reporting in the summary log.

Dec 15, 2014 Project Member #1 lbross@pdx.edu
Hoping to get some items lined up to work on. Could you provide more information on this issue? If you replied and I missed it, I apologize.

Dec 16, 2014 #2 egustafson@fs.fed.us via email
Hi Lesley,

I have not personally experienced this bug. I suggest you ask Brian Miranda or Caren Dymond (cc'd above).

Thanks!

Eric J. Gustafson, PhD

Dec 16, 2014 #3 carendymond
Here's what I found in my notes:

Summarylog.csv duplicates the events in harvest-event-test-log.csv when a prescription is used more than once in a management unit (e.g. with different time periods).

Google code issue #45

**Comment by rmscheller** [comment]
This issue has migrated over to a biomass-harvest-extension issue.
